schema_version = "1.0.0"

id = "blender_mesh_measurements"
name = "Simple Mesh Measurement Tools for Blender"
version = "1.0.0"
tagline = "MeasureIt is cool, but what if you just want to measure something?"
type = "add-on"

maintainer = "Juraji <github@juraji.nl>"
website = "https://github.com/Juraji/blender-mesh-measurements"
tags = ["UI", "Utility"]

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

[build]
paths_exclude_pattern = [
    "/.git/",
    "__pycache__/",
    ".*",
]